using IcpaaS.Core.Telephony;
using Npgsql;
namespace IcpaaS.Api;
public sealed class AgentDeliveryWorker(PlatformStore store,ManagedTelephonyService telephony,CapacityService capacity,ILogger<AgentDeliveryWorker> logger):BackgroundService
{
 sealed record Delivery(Guid Tenant,Guid Campaign,Guid Process,Guid Agent,string Extension,Guid CustomerCall,string Engine,string EngineCall,string Trunk);
 protected override async Task ExecuteAsync(CancellationToken ct){while(!ct.IsCancellationRequested){try{foreach(var x in await Pending(ct))await Ring(x,ct);await BridgeReady(ct);}catch(OperationCanceledException) when(ct.IsCancellationRequested){}catch(Exception e){logger.LogError(e,"Agent delivery cycle failed");}await Task.Delay(250,ct);}}
 async Task<List<Delivery>> Pending(CancellationToken ct){await using var c=await store.Open(ct);await using var q=new NpgsqlCommand(@"SELECT ca.tenant_id,cc.campaign_id,ca.process_id,cc.assigned_agent_id,ae.extension,cu.id,cu.engine_type,cu.engine_call_id,cu.selection_reason FROM campaign_contacts cc JOIN campaigns ca ON ca.id=cc.campaign_id JOIN calls cu ON cu.id=cc.last_call_id JOIN agent_endpoints ae ON ae.user_id=cc.assigned_agent_id AND ae.tenant_id=ca.tenant_id WHERE cc.state='connected' AND cu.ended_at IS NULL AND cu.answered_at IS NOT NULL AND cu.engine_type='freeswitch' AND ae.status<>'break' AND NOT EXISTS(SELECT 1 FROM calls al WHERE al.metadata->>'customerCallId'=cu.id::text) LIMIT 20",c);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<Delivery>();while(await r.ReadAsync(ct))rows.Add(new(r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetGuid(3),r.GetString(4),r.GetGuid(5),r.GetString(6),r.GetString(7),r.GetString(8)));return rows;}
 async Task Ring(Delivery x,CancellationToken ct){var id=Guid.NewGuid();try{await capacity.Reserve(x.Tenant,id,x.Process,ct);await using(var c=await store.Open(ct)){await using var claim=new NpgsqlCommand("INSERT INTO calls(id,tenant_id,process_id,campaign_id,engine_type,direction,to_number,state,selection_reason,metadata) VALUES($1,$2,$3,$4,$5,'outbound',$6,'reserving',$7,jsonb_build_object('leg','agent','customerCallId',$8::text,'agentId',$9::text))",c);Add(claim,id,x.Tenant,x.Process,x.Campaign,x.Engine,x.Extension,x.Trunk,x.CustomerCall,x.Agent);await claim.ExecuteNonQueryAsync(ct);}var result=await telephony.OriginateAgent(x.Tenant,id,x.Extension,x.Trunk,x.Engine,ct);await using(var c=await store.Open(ct)){await using var done=new NpgsqlCommand("UPDATE calls SET engine_call_id=$2,state=$3 WHERE id=$1;UPDATE agent_presence SET state='ringing',last_state_at=now() WHERE tenant_id=$4 AND user_id=$5",c);Add(done,id,result.Call.EngineCallId,result.State,x.Tenant,x.Agent);await done.ExecuteNonQueryAsync(ct);}}catch(Exception e){await capacity.Release(x.Tenant,id,ct);await using var c=await store.Open(ct);await using var fail=new NpgsqlCommand("UPDATE calls SET state='failed',ended_at=now(),hangup_cause=$2 WHERE id=$1;UPDATE agent_presence SET state='available',last_state_at=now() WHERE tenant_id=$3 AND user_id=$4",c);Add(fail,id,e.Message[..Math.Min(500,e.Message.Length)],x.Tenant,x.Agent);await fail.ExecuteNonQueryAsync(ct);logger.LogWarning(e,"Could not ring agent {Agent}",x.Agent);}}
 async Task BridgeReady(CancellationToken ct){await using var c=await store.Open(ct);await using var q=new NpgsqlCommand(@"SELECT al.id,al.tenant_id,al.engine_type,al.engine_call_id,al.selection_reason,(al.metadata->>'customerCallId')::uuid,cu.engine_call_id FROM calls al JOIN calls cu ON cu.id=(al.metadata->>'customerCallId')::uuid WHERE al.metadata->>'leg'='agent' AND al.state='connected' AND coalesce((al.metadata->>'bridged')::boolean,false)=false AND al.ended_at IS NULL AND cu.ended_at IS NULL LIMIT 20",c);await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<(Guid,Guid,string,string,string,Guid,string)>();while(await r.ReadAsync(ct))rows.Add((r.GetGuid(0),r.GetGuid(1),r.GetString(2),r.GetString(3),r.GetString(4),r.GetGuid(5),r.GetString(6)));await r.CloseAsync();foreach(var x in rows){try{await telephony.Bridge(x.Item2,new(x.Item6,x.Item3,x.Item7),new(x.Item1,x.Item3,x.Item4),x.Item5,ct);await using var mark=new NpgsqlCommand("UPDATE calls SET metadata=metadata||'{\"bridged\":true}'::jsonb WHERE id=$1;UPDATE agent_presence SET state='on_call',last_state_at=now() WHERE tenant_id=$2 AND user_id=(SELECT (metadata->>'agentId')::uuid FROM calls WHERE id=$1)",c);Add(mark,x.Item1,x.Item2);await mark.ExecuteNonQueryAsync(ct);}catch(Exception e){logger.LogWarning(e,"Could not bridge agent call {Call}",x.Item1);}}}
 static void Add(NpgsqlCommand q,params object?[] values){foreach(var value in values)q.Parameters.AddWithValue(value??DBNull.Value);}
}
