using System.Security.Claims;
using Npgsql;

namespace IcpaaS.Api;
public sealed record ContactResourceState(bool Enabled);
public sealed record LifecycleProcessUpdate(string Name,string ProcessType,Guid? DidId,Guid? QueueId,decimal MaxCps,bool NumberMasking,int MaxAttempts,int RetryDelayMinutes,bool RecordingEnabled,Guid[] AgentIds,Guid[] DispositionIds);
public sealed record LifecycleCampaignUpdate(string Name,Guid ProcessId,Guid? ListId,string DialerMode,decimal MaxCps,int MaxChannels,bool NumberMasking);
public sealed record AgentMovement(Guid AgentId,Guid? FromProcessId,Guid ToProcessId,int Priority=100);
public static class ContactCenterLifecycleEndpoints
{
 static Guid Tenant(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue("tenant_id")??throw new UnauthorizedAccessException("Tenant required"));
 static bool Operator(ClaimsPrincipal u)=>u.IsInRole("tenant_owner")||u.IsInRole("tenant_admin")||u.IsInRole("supervisor");
 public static void MapContactCenterLifecycle(this WebApplication app)
 {
  var api=app.MapGroup("/api/v1/contact-center").RequireAuthorization();
  api.MapPatch("/{resource}/{id:guid}/state",async(string resource,Guid id,ContactResourceState b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u))return Results.Forbid();var table=resource switch{"queues"=>"contact_queues","dispositions"=>"dispositions","processes"=>"processes",_=>null};if(table is null)return Results.BadRequest(new{error="Unknown contact-center resource"});await using var c=await s.Open(ct);var updated=table=="dispositions"?"":",updated_at=now()";await using var q=new NpgsqlCommand($"UPDATE {table} SET enabled=$3{updated} WHERE id=$1 AND tenant_id=$2 RETURNING id,enabled",c);Add(q,id,Tenant(u),b.Enabled);var row=await One(q,ct);return row is null?Results.NotFound():Results.Ok(row);
  });
  api.MapPost("/agents/move",async(AgentMovement b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u))return Results.Forbid();var tenant=Tenant(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);
   if(b.FromProcessId is not null){await using var remove=new NpgsqlCommand("DELETE FROM process_agents pa USING processes p WHERE pa.process_id=p.id AND pa.user_id=$1 AND pa.process_id=$2 AND p.tenant_id=$3",c,tx);Add(remove,b.AgentId,b.FromProcessId,tenant);await remove.ExecuteNonQueryAsync(ct);}
   await using var add=new NpgsqlCommand("INSERT INTO process_agents(process_id,user_id,priority,enabled) SELECT $1,$2,$3,true WHERE EXISTS(SELECT 1 FROM processes WHERE id=$1 AND tenant_id=$4) AND EXISTS(SELECT 1 FROM users WHERE id=$2 AND tenant_id=$4 AND 'agent'=ANY(roles)) ON CONFLICT(process_id,user_id) DO UPDATE SET priority=excluded.priority,enabled=true",c,tx);Add(add,b.ToProcessId,b.AgentId,b.Priority,tenant);if(await add.ExecuteNonQueryAsync(ct)==0){await tx.RollbackAsync(ct);return Results.BadRequest(new{error="Invalid agent or target process"});}await tx.CommitAsync(ct);return Results.Ok(new{b.AgentId,b.FromProcessId,b.ToProcessId,b.Priority});
  });
  api.MapGet("/processes/{id:guid}",async(Guid id,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT p.id,p.name,p.process_type,p.did_id,p.queue_id,p.max_cps,p.number_masking,p.max_attempts,p.retry_delay_minutes,p.recording_enabled,p.enabled,coalesce(array_agg(DISTINCT pa.user_id) FILTER(WHERE pa.user_id IS NOT NULL),'{}') agent_ids,coalesce(array_agg(DISTINCT pd.disposition_id) FILTER(WHERE pd.disposition_id IS NOT NULL),'{}') disposition_ids FROM processes p LEFT JOIN process_agents pa ON pa.process_id=p.id LEFT JOIN process_dispositions pd ON pd.process_id=p.id WHERE p.id=$1 AND p.tenant_id=$2 GROUP BY p.id",c);Add(q,id,Tenant(u));var row=await One(q,ct);return row is null?Results.NotFound():Results.Ok(row);
  });
  api.MapPatch("/processes/{id:guid}",async(Guid id,LifecycleProcessUpdate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u)||b.AgentIds.Length==0||b.DispositionIds.Length==0)return Results.BadRequest(new{error="Agents and dispositions are required"});var tenant=Tenant(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);
   await using var q=new NpgsqlCommand(@"UPDATE processes SET name=$3,process_type=$4,did_id=$5,queue_id=$6,max_cps=$7,number_masking=$8,max_attempts=$9,retry_delay_minutes=$10,recording_enabled=$11,updated_at=now() WHERE id=$1 AND tenant_id=$2 AND NOT EXISTS(SELECT 1 FROM campaigns WHERE process_id=$1 AND state='running') RETURNING id",c,tx);Add(q,id,tenant,b.Name,b.ProcessType,b.DidId,b.QueueId,b.MaxCps,b.NumberMasking,b.MaxAttempts,b.RetryDelayMinutes,b.RecordingEnabled);if(await q.ExecuteScalarAsync(ct) is null){await tx.RollbackAsync(ct);return Results.Conflict(new{error="Stop running campaigns before editing this process"});}
   await using(var clearAgents=new NpgsqlCommand("DELETE FROM process_agents WHERE process_id=$1",c,tx)){Add(clearAgents,id);await clearAgents.ExecuteNonQueryAsync(ct);}await using(var clearDispositions=new NpgsqlCommand("DELETE FROM process_dispositions WHERE process_id=$1",c,tx)){Add(clearDispositions,id);await clearDispositions.ExecuteNonQueryAsync(ct);}
   foreach(var agent in b.AgentIds){await using var x=new NpgsqlCommand("INSERT INTO process_agents(process_id,user_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM users WHERE id=$2 AND tenant_id=$3 AND 'agent'=ANY(roles))",c,tx);Add(x,id,agent,tenant);await x.ExecuteNonQueryAsync(ct);}foreach(var disposition in b.DispositionIds){await using var x=new NpgsqlCommand("INSERT INTO process_dispositions(process_id,disposition_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM dispositions WHERE id=$2 AND tenant_id=$3)",c,tx);Add(x,id,disposition,tenant);await x.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Results.Ok(new{id});
  });
  api.MapGet("/campaigns/{id:guid}",async(Guid id,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("SELECT id,name,process_id,list_id,dialer_mode,state,max_cps,max_channels,number_masking,scheduled_at FROM campaigns WHERE id=$1 AND tenant_id=$2",c);Add(q,id,Tenant(u));var row=await One(q,ct);return row is null?Results.NotFound():Results.Ok(row);});
  api.MapPatch("/campaigns/{id:guid}",async(Guid id,LifecycleCampaignUpdate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u))return Results.Forbid();var tenant=Tenant(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand(@"UPDATE campaigns SET name=$3,process_id=$4,list_id=$5,dialer_mode=$6,max_cps=$7,max_channels=$8,number_masking=$9,updated_at=now() WHERE id=$1 AND tenant_id=$2 AND state<>'running' AND EXISTS(SELECT 1 FROM processes WHERE id=$4 AND tenant_id=$2) RETURNING id",c,tx);Add(q,id,tenant,b.Name,b.ProcessId,b.ListId,b.DialerMode,b.MaxCps,b.MaxChannels,b.NumberMasking);if(await q.ExecuteScalarAsync(ct) is null){await tx.RollbackAsync(ct);return Results.Conflict(new{error="Stop campaign before editing"});}if(b.ListId is not null){await using var seed=new NpgsqlCommand("INSERT INTO campaign_contacts(campaign_id,contact_id) SELECT $1,id FROM contacts WHERE list_id=$2 AND tenant_id=$3 AND state IN('fresh','callback') ON CONFLICT DO NOTHING",c,tx);Add(seed,id,b.ListId,tenant);await seed.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Results.Ok(new{id});
  });
  api.MapGet("/rechurn",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT r.id,r.state,r.eligible_count,r.queued_count,r.created_at,r.completed_at,sc.name source_campaign,tc.name target_campaign FROM rechurn_jobs r JOIN campaigns sc ON sc.id=r.source_campaign_id JOIN campaigns tc ON tc.id=r.target_campaign_id WHERE r.tenant_id=$1 ORDER BY r.created_at DESC LIMIT 100",c);Add(q,Tenant(u));return Results.Ok(await Rows(q,ct));});
  api.MapGet("/lists/{id:guid}/summary",async(Guid id,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT l.id,l.name,l.status,l.total_rows,l.valid_rows,l.duplicate_rows,count(*) FILTER(WHERE ct.state='fresh') fresh,count(*) FILTER(WHERE ct.state='queued') queued,count(*) FILTER(WHERE ct.state='callback') callback,count(*) FILTER(WHERE ct.state='completed') completed,count(*) FILTER(WHERE ct.state='invalid') invalid,coalesce(sum(ct.attempt_count),0) attempts FROM contact_lists l LEFT JOIN contacts ct ON ct.list_id=l.id WHERE l.id=$1 AND l.tenant_id=$2 GROUP BY l.id",c);Add(q,id,Tenant(u));var row=await One(q,ct);return row is null?Results.NotFound():Results.Ok(row);
  });
  api.MapPatch("/lists/{id:guid}/archive",async(Guid id,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("UPDATE contact_lists SET status='archived' WHERE id=$1 AND tenant_id=$2 RETURNING id,status",c);Add(q,id,Tenant(u));var row=await One(q,ct);return row is null?Results.NotFound():Results.Ok(row);
  });
  api.MapGet("/campaigns/{id:guid}/contacts",async(Guid id,string? state,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT cc.contact_id,cc.state campaign_state,cc.attempts attempt_count,cc.assigned_agent_id,cc.last_error,cc.queued_at,ct.phone_number,ct.first_name,ct.last_name,ct.external_id,ct.last_disposition_id,d.name disposition_name,ct.next_callback_at next_attempt_at FROM campaign_contacts cc JOIN campaigns ca ON ca.id=cc.campaign_id JOIN contacts ct ON ct.id=cc.contact_id LEFT JOIN dispositions d ON d.id=ct.last_disposition_id WHERE cc.campaign_id=$1 AND ca.tenant_id=$2 AND ($3 IS NULL OR cc.state=$3) ORDER BY cc.updated_at DESC LIMIT 500",c);Add(q,id,Tenant(u),(object?)state??DBNull.Value);return Results.Ok(await Rows(q,ct));
  });
 }
 static void Add(NpgsqlCommand c,params object?[] v){foreach(var x in v)c.Parameters.AddWithValue(x??DBNull.Value);}
 static async Task<object?> One(NpgsqlCommand c,CancellationToken ct){await using var r=await c.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);return d;}
 static async Task<List<Dictionary<string,object?>>> Rows(NpgsqlCommand c,CancellationToken ct){await using var r=await c.ExecuteReaderAsync(ct);var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync(ct)){var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);rows.Add(d);}return rows;}
}