using System.Security.Claims;
using System.Text.Json;
using System.Text.RegularExpressions;
using Npgsql;

namespace IcpaaS.Api;

public sealed record QueueCreate(string Name,string Strategy,int MaxWaitSeconds,int WrapUpSeconds);
public sealed record DispositionCreate(string Name,string Code,string Category,Guid? ParentId,bool Callable,bool RequiresRemark,bool CallbackRequired);
public sealed record ContactImportRow(string PhoneNumber,string? FirstName,string? LastName,string? ExternalId,JsonElement? Attributes,string? ConsentStatus=null,DateTimeOffset? ConsentAt=null,string? ConsentSource=null);
public sealed record ContactListImport(string Name,string? SourceFilename,ContactImportRow[] Rows);
public sealed record ContactProcessCreate(string Name,string ProcessType,Guid? DidId,Guid? QueueId,decimal MaxCps,bool NumberMasking,int MaxAttempts,int RetryDelayMinutes,bool RecordingEnabled,Guid[] AgentIds,Guid[] DispositionIds,string CallingTimezone="UTC",int[]? CallingDays=null,TimeOnly? CallingStart=null,TimeOnly? CallingEnd=null,bool RequireConsent=false);
public sealed record ContactCampaignCreate(Guid ProcessId,Guid? ListId,string Name,string DialerMode,decimal MaxCps,int MaxChannels,bool NumberMasking,DateTimeOffset? ScheduledAt);
public sealed record CampaignAction(string Action);
public sealed record OutcomeCreate(Guid? CallId,Guid? CampaignId,Guid ContactId,Guid DispositionId,Guid? SubDispositionId,string? Remark,DateTimeOffset? CallbackAt);
public sealed record RechurnCreate(Guid SourceCampaignId,Guid TargetCampaignId,Guid[] DispositionIds);
public sealed record PresenceChange(string State,Guid? ProcessId,Guid? CampaignId);
public sealed record AgentLeadClaim(Guid CampaignId);
public sealed record DncCreate(string PhoneNumber,string? Reason,string? Source,DateTimeOffset? ExpiresAt);
public sealed record DialComplianceCheck(string PhoneNumber);

public static class ContactCenterEndpoints
{
 static Guid Tenant(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue("tenant_id")??throw new UnauthorizedAccessException("Tenant required"));
 static Guid User(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue(ClaimTypes.NameIdentifier)??u.FindFirstValue("sub")!);
 static bool Admin(ClaimsPrincipal u)=>u.IsInRole("tenant_owner")||u.IsInRole("tenant_admin");
 static bool Operator(ClaimsPrincipal u)=>Admin(u)||u.IsInRole("supervisor");
 public static void MapContactCenter(this WebApplication app)
 {
  var api=app.MapGroup("/api/v1/contact-center").RequireAuthorization();
  api.MapGet("/metadata",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   var tenant=Tenant(u);await using var c=await s.Open(ct);
   return Results.Ok(new{
    queues=await Rows(new NpgsqlCommand("SELECT id,name,strategy,max_wait_seconds,wrap_up_seconds,enabled FROM contact_queues WHERE tenant_id=$1 ORDER BY name",c).With(tenant),ct),
    dispositions=await Rows(new NpgsqlCommand("SELECT id,name,code,category,parent_id,callable,requires_remark,callback_required,enabled FROM dispositions WHERE tenant_id=$1 ORDER BY sort_order,name",c).With(tenant),ct),
    agents=await Rows(new NpgsqlCommand("SELECT id,email,display_name,roles,status FROM users WHERE tenant_id=$1 AND 'agent'=ANY(roles) ORDER BY display_name",c).With(tenant),ct),
    dids=await Rows(new NpgsqlCommand("SELECT id,number_e164,enabled FROM dids WHERE tenant_id=$1 ORDER BY number_e164",c).With(tenant),ct),
    lists=await Rows(new NpgsqlCommand("SELECT id,name,source_filename,total_rows,valid_rows,duplicate_rows,status,created_at FROM contact_lists WHERE tenant_id=$1 ORDER BY created_at DESC",c).With(tenant),ct)
   });
  });
  api.MapPost("/queues",async(QueueCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Admin(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("INSERT INTO contact_queues(tenant_id,name,strategy,max_wait_seconds,wrap_up_seconds) VALUES($1,$2,$3,$4,$5) RETURNING id,name,strategy,max_wait_seconds,wrap_up_seconds,enabled",c);Add(q,Tenant(u),b.Name,b.Strategy,b.MaxWaitSeconds,b.WrapUpSeconds);return Results.Created("/api/v1/contact-center/queues",await One(q,ct));
  });
  api.MapPost("/dispositions",async(DispositionCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Admin(u)||!Regex.IsMatch(b.Code,"^[A-Z0-9_]{2,40}$"))return Results.BadRequest(new{error="Invalid disposition"});await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("INSERT INTO dispositions(tenant_id,name,code,category,parent_id,callable,requires_remark,callback_required) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,name,code,category,parent_id,callable",c);Add(q,Tenant(u),b.Name,b.Code,b.Category,b.ParentId,b.Callable,b.RequiresRemark,b.CallbackRequired);return Results.Created("/api/v1/contact-center/dispositions",await One(q,ct));
  });
  api.MapPost("/lists/import",async(ContactListImport b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u)||b.Rows.Length==0||b.Rows.Length>100000)return Results.BadRequest(new{error="Import must contain 1-100000 rows"});var tenant=Tenant(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var list=new NpgsqlCommand("INSERT INTO contact_lists(tenant_id,name,source_filename,total_rows,status,created_by) VALUES($1,$2,$3,$4,'uploading',$5) RETURNING id",c,tx);Add(list,tenant,b.Name,b.SourceFilename,b.Rows.Length,User(u));var listId=(Guid)(await list.ExecuteScalarAsync(ct))!;var valid=0;var duplicate=0;
   foreach(var row in b.Rows){var phone=Regex.Replace(row.PhoneNumber??"","[^0-9+]","");var consent=(row.ConsentStatus??"unknown").ToLowerInvariant();if(!Regex.IsMatch(phone,"^\\+?[1-9][0-9]{6,14}$")||consent is not ("unknown" or "granted" or "revoked"))continue;await using var q=new NpgsqlCommand("INSERT INTO contacts(tenant_id,list_id,phone_number,first_name,last_name,external_id,attributes,consent_status,consent_at,consent_source) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10) ON CONFLICT(list_id,phone_number) DO NOTHING",c,tx);Add(q,tenant,listId,phone,row.FirstName,row.LastName,row.ExternalId,row.Attributes?.GetRawText()??"{}",consent,row.ConsentAt,row.ConsentSource);var n=await q.ExecuteNonQueryAsync(ct);valid+=n;duplicate+=n==0?1:0;}
   await using var done=new NpgsqlCommand("UPDATE contact_lists SET valid_rows=$2,duplicate_rows=$3,status='ready' WHERE id=$1",c,tx);Add(done,listId,valid,duplicate);await done.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return Results.Created($"/api/v1/contact-center/lists/{listId}",new{id=listId,total=b.Rows.Length,valid,duplicate,invalid=b.Rows.Length-valid-duplicate});
  });
  api.MapGet("/processes",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT p.id,p.name,p.process_type,p.max_cps,p.number_masking,p.max_attempts,p.retry_delay_minutes,p.recording_enabled,p.enabled,p.calling_timezone,p.calling_days,p.calling_start,p.calling_end,p.require_consent,q.name queue_name,d.number_e164 did_number,(SELECT count(*) FROM process_agents pa WHERE pa.process_id=p.id) agent_count,(SELECT count(*) FROM process_dispositions pd WHERE pd.process_id=p.id) disposition_count FROM processes p LEFT JOIN contact_queues q ON q.id=p.queue_id LEFT JOIN dids d ON d.id=p.did_id WHERE p.tenant_id=$1 ORDER BY p.created_at DESC",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));});
  api.MapPost("/processes",async(ContactProcessCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Admin(u)||b.AgentIds.Length==0||b.DispositionIds.Length==0||!ValidTimezone(b.CallingTimezone)||!ValidDays(b.CallingDays))return Results.BadRequest(new{error="Process requires agents, dispositions and a valid calling window"});var tenant=Tenant(u);var callingDays=(b.CallingDays??[1,2,3,4,5,6]).Select(x=>(short)x).ToArray();await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("INSERT INTO processes(tenant_id,name,process_type,did_id,queue_id,max_cps,number_masking,max_attempts,retry_delay_minutes,recording_enabled,calling_timezone,calling_days,calling_start,calling_end,require_consent) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id",c,tx);Add(q,tenant,b.Name,b.ProcessType,b.DidId,b.QueueId,b.MaxCps,b.NumberMasking,b.MaxAttempts,b.RetryDelayMinutes,b.RecordingEnabled,b.CallingTimezone,callingDays,b.CallingStart??new TimeOnly(9,0),b.CallingEnd??new TimeOnly(20,0),b.RequireConsent);var id=(Guid)(await q.ExecuteScalarAsync(ct))!;foreach(var agent in b.AgentIds){await using var a=new NpgsqlCommand("INSERT INTO process_agents(process_id,user_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM users WHERE id=$2 AND tenant_id=$3 AND 'agent'=ANY(roles))",c,tx);Add(a,id,agent,tenant);await a.ExecuteNonQueryAsync(ct);}foreach(var disposition in b.DispositionIds){await using var d=new NpgsqlCommand("INSERT INTO process_dispositions(process_id,disposition_id) SELECT $1,$2 WHERE EXISTS(SELECT 1 FROM dispositions WHERE id=$2 AND tenant_id=$3)",c,tx);Add(d,id,disposition,tenant);await d.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Results.Created($"/api/v1/contact-center/processes/{id}",new{id,b.Name,b.ProcessType,b.MaxCps,b.NumberMasking});
  });
  api.MapGet("/compliance/dnc",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Operator(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("SELECT id,phone_normalized,reason,source,expires_at,created_at FROM tenant_dnc WHERE tenant_id=$1 ORDER BY created_at DESC LIMIT 1000",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));});
  api.MapPost("/compliance/dnc",async(DncCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Operator(u))return Results.Forbid();var phone=NormalizePhone(b.PhoneNumber);if(phone is null)return Results.BadRequest(new{error="Invalid DNC number"});await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("INSERT INTO tenant_dnc(tenant_id,phone_normalized,reason,source,expires_at,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,phone_normalized) DO UPDATE SET reason=excluded.reason,source=excluded.source,expires_at=excluded.expires_at RETURNING id,phone_normalized,reason,source,expires_at,created_at",c);Add(q,Tenant(u),phone,b.Reason,string.IsNullOrWhiteSpace(b.Source)?"manual":b.Source,b.ExpiresAt,User(u));return Results.Ok(await One(q,ct));});
  api.MapDelete("/compliance/dnc/{id:guid}",async(Guid id,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Admin(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("DELETE FROM tenant_dnc WHERE id=$1 AND tenant_id=$2",c);Add(q,id,Tenant(u));return await q.ExecuteNonQueryAsync(ct)==1?Results.NoContent():Results.NotFound();});
  api.MapGet("/compliance/events",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Operator(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("SELECT id,campaign_id,contact_id,rule,decision,detail,occurred_at FROM dialing_compliance_events WHERE tenant_id=$1 ORDER BY occurred_at DESC LIMIT 500",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));});
  api.MapPost("/compliance/check",async(DialComplianceCheck b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{var tenant=Tenant(u);var phone=NormalizePhone(b.PhoneNumber);if(phone is null)return Results.BadRequest(new{error="Invalid destination"});await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT CASE
WHEN EXISTS(SELECT 1 FROM tenant_dnc d WHERE d.tenant_id=$1 AND d.phone_normalized=$2 AND (d.expires_at IS NULL OR d.expires_at>now())) THEN 'dnc'
WHEN NOT EXISTS(SELECT 1 FROM process_agents pa JOIN campaigns ca ON ca.process_id=pa.process_id AND ca.state='running' AND ca.dialer_mode IN('manual','preview') JOIN processes p ON p.id=ca.process_id WHERE pa.user_id=$3 AND p.tenant_id=$1 AND pa.enabled AND extract(isodow FROM now() AT TIME ZONE p.calling_timezone)::smallint=ANY(p.calling_days) AND (CASE WHEN p.calling_start<p.calling_end THEN (now() AT TIME ZONE p.calling_timezone)::time>=p.calling_start AND (now() AT TIME ZONE p.calling_timezone)::time<p.calling_end ELSE (now() AT TIME ZONE p.calling_timezone)::time>=p.calling_start OR (now() AT TIME ZONE p.calling_timezone)::time<p.calling_end END)) THEN 'outside_calling_window'
ELSE NULL END",c);Add(q,tenant,phone,User(u));var rule=await q.ExecuteScalarAsync(ct) as string;await using var audit=new NpgsqlCommand("INSERT INTO dialing_compliance_events(tenant_id,rule,decision,detail) VALUES($1,$2,$3,jsonb_build_object('phoneLast4',right($4,4),'source','manual_dial'))",c);Add(audit,tenant,rule??"manual_check",rule is null?"allowed":"blocked",phone);await audit.ExecuteNonQueryAsync(ct);if(rule is not null)return Results.Conflict(new{error=$"Dial blocked by compliance rule: {rule}",rule});return Results.Ok(new{allowed=true});});
  api.MapGet("/campaigns",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT c.id,c.name,c.dialer_mode,c.state,c.max_cps,c.max_channels,c.number_masking,c.scheduled_at,c.started_at,c.stopped_at,p.name process_name,l.name list_name,count(cc.contact_id) total_contacts,count(*) FILTER(WHERE cc.state='queued') queued,count(*) FILTER(WHERE cc.state='dialing') dialing,count(*) FILTER(WHERE cc.state='connected') connected,count(*) FILTER(WHERE cc.state='disposed') disposed,count(*) FILTER(WHERE cc.state='callback') callback FROM campaigns c JOIN processes p ON p.id=c.process_id LEFT JOIN contact_lists l ON l.id=c.list_id LEFT JOIN campaign_contacts cc ON cc.campaign_id=c.id WHERE c.tenant_id=$1 GROUP BY c.id,p.name,l.name ORDER BY c.created_at DESC",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));});
  api.MapPost("/campaigns",async(ContactCampaignCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u))return Results.Forbid();var tenant=Tenant(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("INSERT INTO campaigns(tenant_id,process_id,list_id,name,dialer_mode,max_cps,max_channels,number_masking,scheduled_at) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 WHERE EXISTS(SELECT 1 FROM processes WHERE id=$2 AND tenant_id=$1) RETURNING id",c,tx);Add(q,tenant,b.ProcessId,b.ListId,b.Name,b.DialerMode,b.MaxCps,b.MaxChannels,b.NumberMasking,b.ScheduledAt);var raw=await q.ExecuteScalarAsync(ct);if(raw is null)return Results.BadRequest(new{error="Invalid process"});var id=(Guid)raw;if(b.ListId is not null){await using var seed=new NpgsqlCommand("INSERT INTO campaign_contacts(campaign_id,contact_id) SELECT $1,id FROM contacts WHERE list_id=$2 AND tenant_id=$3 AND state IN('fresh','callback') ON CONFLICT DO NOTHING",c,tx);Add(seed,id,b.ListId,tenant);await seed.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Results.Created($"/api/v1/contact-center/campaigns/{id}",new{id,b.Name,b.DialerMode,state="draft"});
  });
  api.MapPatch("/campaigns/{id:guid}/state",async(Guid id,CampaignAction b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u))return Results.Forbid();var next=b.Action.ToLowerInvariant();var allowed=next switch{"start"=>"running","resume"=>"running","pause"=>"paused","stop"=>"completed","archive"=>"archived",_=>null};if(allowed is null)return Results.BadRequest(new{error="Unknown action"});await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("UPDATE campaigns SET state=$3,started_at=CASE WHEN $3='running' AND started_at IS NULL THEN now() ELSE started_at END,stopped_at=CASE WHEN $3 IN('completed','archived') THEN now() ELSE stopped_at END,updated_at=now() WHERE id=$1 AND tenant_id=$2 RETURNING id,name,state,started_at,stopped_at",c);Add(q,id,Tenant(u),allowed);return await One(q,ct) is { } row?Results.Ok(row):Results.NotFound();
  });
  api.MapPost("/outcomes",async(OutcomeCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   var tenant=Tenant(u);var agent=User(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand("INSERT INTO call_outcomes(tenant_id,call_id,campaign_id,contact_id,agent_user_id,disposition_id,sub_disposition_id,remark,callback_at) SELECT $1,$2,$3,$4,$5,$6,$7,$8,$9 WHERE EXISTS(SELECT 1 FROM dispositions WHERE id=$6 AND tenant_id=$1) AND EXISTS(SELECT 1 FROM contacts WHERE id=$4 AND tenant_id=$1) AND ($3 IS NULL OR EXISTS(SELECT 1 FROM campaign_contacts cc JOIN campaigns ca ON ca.id=cc.campaign_id WHERE cc.campaign_id=$3 AND cc.contact_id=$4 AND cc.assigned_agent_id=$5 AND ca.tenant_id=$1)) RETURNING id",c,tx);Add(q,tenant,b.CallId,b.CampaignId,b.ContactId,agent,b.DispositionId,b.SubDispositionId,b.Remark,b.CallbackAt);var id=await q.ExecuteScalarAsync(ct);if(id is null)return Results.BadRequest(new{error="Invalid disposition or lead assignment"});await using var update=new NpgsqlCommand("UPDATE contacts SET last_disposition_id=$2,last_called_at=now(),next_callback_at=$3,state=CASE WHEN $3 IS NOT NULL THEN 'callback' WHEN EXISTS(SELECT 1 FROM dispositions WHERE id=$2 AND callable) THEN 'fresh' ELSE 'completed' END WHERE id=$1 AND tenant_id=$4",c,tx);Add(update,b.ContactId,b.DispositionId,b.CallbackAt,tenant);await update.ExecuteNonQueryAsync(ct);if(b.CampaignId is not null){await using var cc=new NpgsqlCommand("UPDATE campaign_contacts SET state=CASE WHEN $3 IS NOT NULL THEN 'callback' ELSE 'disposed' END,updated_at=now() WHERE campaign_id=$1 AND contact_id=$2",c,tx);Add(cc,b.CampaignId,b.ContactId,b.CallbackAt);await cc.ExecuteNonQueryAsync(ct);await using var wrap=new NpgsqlCommand("UPDATE agent_presence SET state='wrap_up',last_state_at=now() WHERE tenant_id=$1 AND user_id=$2 AND campaign_id=$3",c,tx);Add(wrap,tenant,agent,b.CampaignId);await wrap.ExecuteNonQueryAsync(ct);}await tx.CommitAsync(ct);return Results.Created("/api/v1/contact-center/outcomes",new{id});
  });
  api.MapPost("/rechurn",async(RechurnCreate b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   if(!Operator(u)||b.DispositionIds.Length==0)return Results.BadRequest(new{error="Select dispositions"});var tenant=Tenant(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var job=new NpgsqlCommand("INSERT INTO rechurn_jobs(tenant_id,source_campaign_id,target_campaign_id,disposition_ids,state,created_by) VALUES($1,$2,$3,$4,'running',$5) RETURNING id",c,tx);Add(job,tenant,b.SourceCampaignId,b.TargetCampaignId,b.DispositionIds,User(u));var id=(Guid)(await job.ExecuteScalarAsync(ct))!;await using var seed=new NpgsqlCommand(@"INSERT INTO campaign_contacts(campaign_id,contact_id) SELECT $1,o.contact_id FROM call_outcomes o WHERE o.tenant_id=$2 AND o.campaign_id=$3 AND (o.disposition_id=ANY($4) OR o.sub_disposition_id=ANY($4)) AND o.contact_id IS NOT NULL ON CONFLICT DO NOTHING",c,tx);Add(seed,b.TargetCampaignId,tenant,b.SourceCampaignId,b.DispositionIds);var queued=await seed.ExecuteNonQueryAsync(ct);await using var done=new NpgsqlCommand("UPDATE rechurn_jobs SET state='completed',eligible_count=$2,queued_count=$2,completed_at=now() WHERE id=$1",c,tx);Add(done,id,queued);await done.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return Results.Created($"/api/v1/contact-center/rechurn/{id}",new{id,queued});
  });
  api.MapGet("/agent/workspace",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{
   var tenant=Tenant(u);var user=User(u);await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT cc.campaign_id,c.name campaign_name,c.dialer_mode,cc.contact_id,CASE WHEN p.number_masking THEN concat('******',right(ct.phone_number,4)) ELSE ct.phone_number END phone_number,CASE WHEN p.number_masking THEN NULL ELSE ct.phone_number END dial_number,p.number_masking,ct.first_name,ct.last_name,ct.state,ct.attempt_count,ct.attributes,ct.next_callback_at FROM campaigns c JOIN processes p ON p.id=c.process_id JOIN campaign_contacts cc ON cc.campaign_id=c.id JOIN contacts ct ON ct.id=cc.contact_id WHERE c.state='running' AND p.tenant_id=$2 AND cc.assigned_agent_id=$1 AND cc.state IN('reserved','dialing','connected') ORDER BY cc.updated_at DESC LIMIT 20",c);Add(q,user,tenant);return Results.Ok(await Rows(q,ct));
  });
  api.MapGet("/agent/campaigns",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT ca.id,ca.name,ca.dialer_mode,p.number_masking,count(cc.contact_id) FILTER(WHERE cc.state IN('queued','callback')) available_leads FROM process_agents pa JOIN campaigns ca ON ca.process_id=pa.process_id AND ca.state='running' JOIN processes p ON p.id=ca.process_id LEFT JOIN campaign_contacts cc ON cc.campaign_id=ca.id WHERE pa.user_id=$1 AND p.tenant_id=$2 AND pa.enabled AND ca.dialer_mode IN('manual','preview') GROUP BY ca.id,p.number_masking ORDER BY ca.name",c);Add(q,User(u),Tenant(u));return Results.Ok(await Rows(q,ct));});
  api.MapPost("/agent/leads/claim",async(AgentLeadClaim b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{var tenant=Tenant(u);var user=User(u);await using var c=await s.Open(ct);await using var tx=await c.BeginTransactionAsync(ct);await using var q=new NpgsqlCommand(@"WITH candidate AS(SELECT cc.contact_id FROM campaign_contacts cc JOIN contacts x ON x.id=cc.contact_id JOIN campaigns ca ON ca.id=cc.campaign_id JOIN processes p ON p.id=ca.process_id JOIN process_agents pa ON pa.process_id=ca.process_id AND pa.user_id=$2 AND pa.enabled WHERE cc.campaign_id=$1 AND ca.tenant_id=$3 AND ca.state='running' AND ca.dialer_mode IN('manual','preview') AND (cc.state='queued' OR (cc.state='callback' AND x.next_callback_at<=now())) AND x.consent_status<>'revoked' AND (NOT p.require_consent OR x.consent_status='granted') AND NOT EXISTS(SELECT 1 FROM tenant_dnc d WHERE d.tenant_id=$3 AND d.phone_normalized=regexp_replace(x.phone_number,'[^0-9]','','g') AND (d.expires_at IS NULL OR d.expires_at>now())) AND extract(isodow FROM now() AT TIME ZONE p.calling_timezone)::smallint=ANY(p.calling_days) AND (CASE WHEN p.calling_start<p.calling_end THEN (now() AT TIME ZONE p.calling_timezone)::time>=p.calling_start AND (now() AT TIME ZONE p.calling_timezone)::time<p.calling_end ELSE (now() AT TIME ZONE p.calling_timezone)::time>=p.calling_start OR (now() AT TIME ZONE p.calling_timezone)::time<p.calling_end END) AND NOT EXISTS(SELECT 1 FROM campaign_contacts held WHERE held.assigned_agent_id=$2 AND held.state IN('reserved','dialing','connected')) ORDER BY CASE WHEN cc.state='callback' THEN 0 ELSE 1 END,x.next_callback_at NULLS LAST,cc.queued_at FOR UPDATE OF cc SKIP LOCKED LIMIT 1) UPDATE campaign_contacts cc SET state='reserved',assigned_agent_id=$2,updated_at=now() FROM candidate WHERE cc.campaign_id=$1 AND cc.contact_id=candidate.contact_id RETURNING cc.contact_id",c,tx);Add(q,b.CampaignId,user,tenant);var raw=await q.ExecuteScalarAsync(ct);if(raw is null){await tx.RollbackAsync(ct);return Results.Conflict(new{error="No compliant lead is available inside the configured calling window"});}await using var presence=new NpgsqlCommand("INSERT INTO agent_presence(tenant_id,user_id,campaign_id,state) VALUES($1,$2,$3,'reserved') ON CONFLICT(tenant_id,user_id) DO UPDATE SET campaign_id=$3,state='reserved',last_state_at=now()",c,tx);Add(presence,tenant,user,b.CampaignId);await presence.ExecuteNonQueryAsync(ct);await tx.CommitAsync(ct);return Results.Ok(new{contactId=(Guid)raw});});
  api.MapPut("/agent/presence",async(PresenceChange b,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("INSERT INTO agent_presence(tenant_id,user_id,process_id,campaign_id,state) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id,user_id) DO UPDATE SET process_id=excluded.process_id,campaign_id=excluded.campaign_id,state=excluded.state,last_state_at=now() RETURNING state,last_state_at",c);Add(q,Tenant(u),User(u),b.ProcessId,b.CampaignId,b.State);return Results.Ok(await One(q,ct));});
 }
 static NpgsqlCommand With(this NpgsqlCommand c,object value){c.Parameters.AddWithValue(value);return c;}
 static string? NormalizePhone(string? value){var phone=Regex.Replace(value??"","[^0-9]","");return Regex.IsMatch(phone,"^[1-9][0-9]{6,14}$")?phone:null;}
 static bool ValidTimezone(string value){try{_ = TimeZoneInfo.FindSystemTimeZoneById(value);return true;}catch{return false;}}
 static bool ValidDays(int[]? days)=>days is null||days.Length is >0 and <=7&&days.All(x=>x is >=1 and <=7)&&days.Distinct().Count()==days.Length;
 static void Add(NpgsqlCommand c,params object?[] values){for(var i=0;i<values.Length;i++)c.Parameters.AddWithValue(values[i]??DBNull.Value);}
 static async Task<object?> One(NpgsqlCommand c,CancellationToken ct){await using var r=await c.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return null;var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);return d;}
 static async Task<List<Dictionary<string,object?>>> Rows(NpgsqlCommand c,CancellationToken ct){await using var r=await c.ExecuteReaderAsync(ct);var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync(ct)){var d=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)d[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);rows.Add(d);}return rows;}
}
