using System.Security.Claims;using System.Security.Cryptography;using Npgsql;
namespace IcpaaS.Api;
public static class RecordingEndpoints
{
 const long MaxBytes=50L*1024*1024;static Guid Tenant(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue("tenant_id")??throw new UnauthorizedAccessException("Tenant required"));static bool Review(ClaimsPrincipal u)=>u.IsInRole("tenant_owner")||u.IsInRole("tenant_admin")||u.IsInRole("supervisor")||u.IsInRole("auditor");
 public static void MapRecordings(this WebApplication app){app.MapPut("/internal/recordings/{id:guid}",Upload);var api=app.MapGroup("/api/v1/recordings").RequireAuthorization();api.MapGet("/",List);api.MapGet("/{id:guid}/media",Media);}
 static async Task<IResult> Upload(Guid id,HttpRequest request,PlatformStore store,IConfiguration cfg,CancellationToken ct){var expected=cfg["ICPaaS:Security:NodeKey"]??"";if(expected.Length<24||request.Headers["X-ICPaaS-Node-Key"]!=expected)return Results.Unauthorized();if(request.ContentLength is null or <=0||request.ContentLength>MaxBytes)return Results.StatusCode(StatusCodes.Status413PayloadTooLarge);await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("SELECT storage_key FROM call_recordings WHERE id=$1 AND state IN('recording','awaiting_upload')",c);q.Parameters.AddWithValue(id);var key=await q.ExecuteScalarAsync(ct) as string;if(key is null)return Results.NotFound();var root=cfg["ICPaaS:Recording:StoragePath"]??"/var/lib/icpaas/recordings";var path=Path.Combine(root,key+".wav");var temp=path+".upload";Directory.CreateDirectory(Path.GetDirectoryName(path)!);long size=0;using var hash=IncrementalHash.CreateHash(HashAlgorithmName.SHA256);await using(var output=new FileStream(temp,FileMode.Create,FileAccess.Write,FileShare.None,81920,FileOptions.Asynchronous)){var buffer=new byte[81920];int read;while((read=await request.Body.ReadAsync(buffer,ct))>0){size+=read;if(size>MaxBytes){output.Close();File.Delete(temp);return Results.StatusCode(StatusCodes.Status413PayloadTooLarge);}hash.AppendData(buffer,0,read);await output.WriteAsync(buffer.AsMemory(0,read),ct);}}File.Move(temp,path,true);var sha=Convert.ToHexString(hash.GetHashAndReset()).ToLowerInvariant();await using var done=new NpgsqlCommand("UPDATE call_recordings SET state='ready',content_type='audio/wav',size_bytes=$2,sha256=$3,completed_at=coalesce(completed_at,now()),error=NULL WHERE id=$1",c);Add(done,id,size,sha);await done.ExecuteNonQueryAsync(ct);return Results.Ok(new{id,sizeBytes=size,sha256=sha});}
 static async Task<IResult> List(ClaimsPrincipal u,PlatformStore store,CancellationToken ct){if(!Review(u))return Results.Forbid();await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("SELECT r.id,r.call_id,r.state,r.content_type,r.size_bytes,r.started_at,r.completed_at,r.expires_at,cu.direction,cu.from_number,cu.to_number FROM call_recordings r JOIN calls cu ON cu.id=r.call_id WHERE r.tenant_id=$1 ORDER BY r.created_at DESC LIMIT 500",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));}
 static async Task<IResult> Media(Guid id,ClaimsPrincipal u,PlatformStore store,IConfiguration cfg,CancellationToken ct){if(!Review(u))return Results.Forbid();await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("SELECT storage_key,content_type FROM call_recordings WHERE id=$1 AND tenant_id=$2 AND state='ready' AND expires_at>now()",c);Add(q,id,Tenant(u));await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return Results.NotFound();var key=r.GetString(0);var type=r.IsDBNull(1)?"audio/wav":r.GetString(1);var path=Path.Combine(cfg["ICPaaS:Recording:StoragePath"]??"/var/lib/icpaas/recordings",key+".wav");return File.Exists(path)?Results.File(path,type,enableRangeProcessing:true):Results.NotFound();}
 static void Add(NpgsqlCommand q,params object?[] values){foreach(var v in values)q.Parameters.AddWithValue(v??DBNull.Value);}static async Task<List<Dictionary<string,object?>>> Rows(NpgsqlCommand q,CancellationToken ct){await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync(ct)){var row=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)row[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);rows.Add(row);}return rows;}
}
