using IcpaaS.Core.Telephony;
using Npgsql;
namespace IcpaaS.Api;
public sealed class RecordingWorker(PlatformStore store,ManagedTelephonyService telephony,IConfiguration configuration,ILogger<RecordingWorker> logger):BackgroundService
{
 sealed record RecordingStart(Guid Recording,Guid Tenant,Guid Call,string Engine,string EngineCall,string Trunk,string Key);
 protected override async Task ExecuteAsync(CancellationToken ct){while(!ct.IsCancellationRequested){try{foreach(var x in await Claim(ct))await Begin(x,ct);await FinalizeEnded(ct);await Expire(ct);}catch(OperationCanceledException) when(ct.IsCancellationRequested){}catch(Exception e){logger.LogError(e,"Recording lifecycle cycle failed");}await Task.Delay(1000,ct);}}
 async Task<List<RecordingStart>> Claim(CancellationToken ct){await using var c=await store.Open(ct);const string sql=@"INSERT INTO call_recordings(id,tenant_id,call_id,storage_key,expires_at) SELECT candidate.recording_id,cu.tenant_id,cu.id,cu.tenant_id::text||'/'||candidate.recording_id::text,now()+ts.recording_retention_days*interval '1 day' FROM calls cu JOIN processes p ON p.id=cu.process_id JOIN tenant_settings ts ON ts.tenant_id=cu.tenant_id CROSS JOIN LATERAL (SELECT gen_random_uuid() recording_id) candidate WHERE cu.answered_at IS NOT NULL AND cu.ended_at IS NULL AND p.recording_enabled AND coalesce(cu.metadata->>'leg','customer')='customer' ON CONFLICT(call_id) DO NOTHING RETURNING id,tenant_id,call_id,storage_key";await using var q=new NpgsqlCommand(sql,c);await using var r=await q.ExecuteReaderAsync(ct);var seed=new List<(Guid,Guid,Guid,string)>();while(await r.ReadAsync(ct))seed.Add((r.GetGuid(0),r.GetGuid(1),r.GetGuid(2),r.GetString(3)));await r.CloseAsync();var rows=new List<RecordingStart>();foreach(var x in seed){await using var call=new NpgsqlCommand("SELECT engine_type,engine_call_id,selection_reason FROM calls WHERE id=$1",c);call.Parameters.AddWithValue(x.Item3);await using var cr=await call.ExecuteReaderAsync(ct);if(await cr.ReadAsync(ct)&&!cr.IsDBNull(1)&&!cr.IsDBNull(2))rows.Add(new(x.Item1,x.Item2,x.Item3,cr.GetString(0),cr.GetString(1),cr.GetString(2),x.Item4));await cr.CloseAsync();}return rows;}
 async Task Begin(RecordingStart x,CancellationToken ct){try{await telephony.StartRecording(x.Tenant,new(x.Call,x.Engine,x.EngineCall),x.Trunk,x.Key,ct);await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("UPDATE call_recordings SET state='recording',started_at=now() WHERE id=$1",c);q.Parameters.AddWithValue(x.Recording);await q.ExecuteNonQueryAsync(ct);}catch(Exception e){await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("UPDATE call_recordings SET state='failed',error=$2 WHERE id=$1",c);Add(q,x.Recording,e.Message[..Math.Min(500,e.Message.Length)]);await q.ExecuteNonQueryAsync(ct);logger.LogWarning(e,"Could not start recording {Recording}",x.Recording);}}
 async Task FinalizeEnded(CancellationToken ct){await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("UPDATE call_recordings r SET state='awaiting_upload',completed_at=coalesce(completed_at,cu.ended_at) FROM calls cu WHERE cu.id=r.call_id AND cu.ended_at IS NOT NULL AND r.state='recording'",c);await q.ExecuteNonQueryAsync(ct);}
 async Task Expire(CancellationToken ct){await using var c=await store.Open(ct);await using var q=new NpgsqlCommand("UPDATE call_recordings SET state='expired' WHERE state='ready' AND expires_at<=now() RETURNING id,storage_key",c);await using var r=await q.ExecuteReaderAsync(ct);var files=new List<string>();while(await r.ReadAsync(ct))files.Add(PathFor(r.GetString(1)));await r.CloseAsync();foreach(var file in files)try{if(File.Exists(file))File.Delete(file);}catch(Exception e){logger.LogWarning(e,"Could not delete expired recording {File}",file);}}
 string PathFor(string key)=>Path.Combine(configuration["ICPaaS:Recording:StoragePath"]??"/var/lib/icpaas/recordings",key+".wav");static void Add(NpgsqlCommand q,params object?[] values){foreach(var v in values)q.Parameters.AddWithValue(v??DBNull.Value);}
}
