using System.Security.Claims;
using IcpaaS.Core.Telephony;
using Npgsql;
namespace IcpaaS.Api;
public static class SupervisorEndpoints
{
 static Guid Tenant(ClaimsPrincipal u)=>Guid.Parse(u.FindFirstValue("tenant_id")??throw new UnauthorizedAccessException("Tenant required"));static bool Allowed(ClaimsPrincipal u)=>u.IsInRole("tenant_owner")||u.IsInRole("tenant_admin")||u.IsInRole("supervisor");
 public static void MapSupervisor(this WebApplication app){var api=app.MapGroup("/api/v1/supervisor").RequireAuthorization();
 api.MapGet("/live",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Allowed(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT cu.id,cu.direction,cu.from_number,cu.to_number,cu.state,cu.engine_type,p.name process_name,ca.name campaign_name,cu.selected_at,cu.answered_at,extract(epoch from(now()-coalesce(cu.answered_at,cu.selected_at)))::integer duration_seconds,al.id agent_leg_id,(al.metadata->>'agentId')::uuid agent_id,usr.display_name agent_name,ae.extension,ap.state agent_state FROM calls cu LEFT JOIN processes p ON p.id=cu.process_id LEFT JOIN campaigns ca ON ca.id=cu.campaign_id LEFT JOIN calls al ON al.metadata->>'customerCallId'=cu.id::text AND al.ended_at IS NULL LEFT JOIN users usr ON usr.id=(al.metadata->>'agentId')::uuid LEFT JOIN agent_endpoints ae ON ae.user_id=usr.id AND ae.tenant_id=cu.tenant_id LEFT JOIN agent_presence ap ON ap.user_id=usr.id AND ap.tenant_id=cu.tenant_id WHERE cu.tenant_id=$1 AND cu.ended_at IS NULL AND coalesce(cu.metadata->>'leg','customer')<>'agent' ORDER BY cu.selected_at",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));});
 api.MapGet("/agents",async(ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Allowed(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT usr.id,usr.display_name,usr.email,ae.extension,ae.status endpoint_status,coalesce(ap.state,'offline') state,ap.last_state_at,p.name process_name,ca.name campaign_name,(SELECT count(*) FROM calls x WHERE x.tenant_id=$1 AND x.metadata->>'agentId'=usr.id::text AND x.answered_at IS NOT NULL AND x.created_at::date=current_date) calls_today FROM users usr LEFT JOIN agent_endpoints ae ON ae.user_id=usr.id AND ae.tenant_id=usr.tenant_id LEFT JOIN agent_presence ap ON ap.user_id=usr.id AND ap.tenant_id=usr.tenant_id LEFT JOIN processes p ON p.id=ap.process_id LEFT JOIN campaigns ca ON ca.id=ap.campaign_id WHERE usr.tenant_id=$1 AND 'agent'=ANY(usr.roles) AND usr.status='active' ORDER BY coalesce(ap.state,'offline'),usr.display_name",c);q.Parameters.AddWithValue(Tenant(u));return Results.Ok(await Rows(q,ct));});
 api.MapGet("/calls/{id:guid}",async(Guid id,ClaimsPrincipal u,PlatformStore s,CancellationToken ct)=>{if(!Allowed(u))return Results.Forbid();await using var c=await s.Open(ct);await using var q=new NpgsqlCommand(@"SELECT id,direction,from_number,to_number,state,engine_type,engine_call_id,process_id,campaign_id,selected_at,answered_at,ended_at,hangup_cause,metadata FROM calls WHERE tenant_id=$1 AND (id=$2 OR metadata->>'customerCallId'=$2::text) ORDER BY CASE WHEN id=$2 THEN 0 ELSE 1 END",c);Add(q,Tenant(u),id);var rows=await Rows(q,ct);return rows.Count==0?Results.NotFound():Results.Ok(rows);});
 api.MapPost("/calls/{id:guid}/hangup",async(Guid id,ClaimsPrincipal u,PlatformStore s,ManagedTelephonyService telephony,CancellationToken ct)=>{if(!Allowed(u))return Results.Forbid();var tenant=Tenant(u);await using var c=await s.Open(ct);await using var q=new NpgsqlCommand("UPDATE calls SET state='ending',hangup_cause='SUPERVISOR_HANGUP' WHERE id=$1 AND tenant_id=$2 AND ended_at IS NULL RETURNING engine_type,engine_call_id,selection_reason",c);Add(q,id,tenant);await using var r=await q.ExecuteReaderAsync(ct);if(!await r.ReadAsync(ct))return Results.NotFound();var engine=r.GetString(0);var engineCall=r.IsDBNull(1)?null:r.GetString(1);var trunk=r.IsDBNull(2)?null:r.GetString(2);await r.CloseAsync();if(string.IsNullOrWhiteSpace(engineCall))return Results.Conflict(new{error="Call has no active engine channel"});await telephony.Control(tenant,new(id,engine,engineCall),"hangup",new(null,null,null,"SUPERVISOR_HANGUP"),trunk,ct);return Results.Accepted(value:new{id,state="ending"});});}
 static void Add(NpgsqlCommand q,params object?[] values){foreach(var value in values)q.Parameters.AddWithValue(value??DBNull.Value);}static async Task<List<Dictionary<string,object?>>> Rows(NpgsqlCommand q,CancellationToken ct){await using var r=await q.ExecuteReaderAsync(ct);var rows=new List<Dictionary<string,object?>>();while(await r.ReadAsync(ct)){var row=new Dictionary<string,object?>();for(var i=0;i<r.FieldCount;i++)row[r.GetName(i)]=r.IsDBNull(i)?null:r.GetValue(i);rows.Add(row);}return rows;}
}
